# H2 Database Configuration
spring:
  application:
    name: account-service
  cloud:
    discovery:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka/
  datasource:
    url: jdbc:mysql://localhost:3306/bankapp?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    hikari:
      maximum-pool-size: 50
      minimum-idle: 25
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

# JWT Configuration
jwt:
  secret: s2o8BcRxJoWo59Da6+Zmiq/eKFTGQ8lSnAXudW3ACCS7DnxFKoyfEZAeJw3YuQ9Tw7MBAn5JThJlcC/MBahhdg==
  expiration: 3600

# Tracing and Metrics Configuration
management:
  otlp:
    metrics:
      export:
        enabled: false
  tracing:
    exporter:
      zipkin:
        endpoint: http://localhost:9411/api/v2/spans
    sampling:
      probability: 1.0
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true

# Logging Configuration
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
