spring:
  application:
    name: eureka-server
  cloud:
    eureka:
      client:
        fetch-registry: false
        register-with-eureka: false
      server:
        enable-self-preservation: false
server:
  port: 8761
